# Generated by Django 5.2 on 2025-06-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destinatario', models.EmailField(max_length=254)),
                ('asunto', models.TextField(max_length=250)),
                ('mensaje', models.TextField(max_length=250)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos_adjuntos/')),
            ],
        ),
    ]
